theme_color: # Theme color. Please go to [Colors](https://www.mdui.org/docs/color)
  primary: indigo
  accent: pink

notice: # Notice or announcement. Support `<a>` tag

favicon: /images/unidy.png # Favicon path
banner: /images/banner.png # Sidebar background image path
avatar: /images/unidy.png # Avatar image path
# rss: /atom.xml # RSS link. `hexo-generator-feed` plugin is needed

email: # Email address
sns: # SNS links
  twitter:
  facebook:
  google_plus:
  weibo:
  instagram:
  tumblr:
  github: https://github.com/UNIDY2002/
  linkedin:
  zhihu:
  douban:
  qq:
  wechat:

open_graph: # OpenGraph settings
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification: # Site verification keys
  google:
  baidu:
analytics: # Site analytics IDs
  google_site_id:
  baidu_site_id:
  cnzz_site_id:
pages: # Custom page links. Set with `name` and `link`
  - name: 资源下载
    link: /downloads
  - name: THUInfo
    link: https://thuinfo.net/
links: # Friendship links. Set with `name` and `link`
  - name: 迪兰特的小屋
    link: https://www.dilant.cn/
  - name: Ashitemaru
    link: https://ashitemaru.github.io/
  - name: 猫猫窝
    link: https://zcy.moe/

since: 2021 # Start year, use a 4-digit number. If you don't set the start year, there won't be a "since xxxx" on the bottom of your site
footer_text: # Additional text in footer, such as the record information. Support `<a>` tag
license: # License description of every article. Support `<a>` tag

gallery: # CDN links of `fancybox` plugin used on Gallery page
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi: # Use `busuanzi` plugin to count website visits
  site: false
  page: false
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode: # Qrcode for articles. if use `plugin`, `hexo-helper-qrcode` plugin is needed
  caption: 在移动端上查看
  use: hexo-helper-qrcode
donate: # Use your payment qrcode or link to receive donations. Set with `name` and `link`
search: # Search settings. if use `plugin`, `hexo-generator-search` plugin is needed and `path` should be set correctly
  placeholder: 请输入关键字
  path: /search.xml
  use: plugin
comment: # Comment plugin settings. Set `use` with the plugin name such as `gitalk`
  use: valine
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  livere_data_uid:
  valine_leancloud_app_id: ewlT3sErBcbbAdwPXrhxRNfg-gzGzoHsz
  valine_leancloud_app_key: MQgeLEsEGHvbeG6SjqBaiUad
  valine_placeholder: '一起来评论呀~'
  valine_page_size:
  valine_avatar: 'mp'
  valine_lang:
  valine_guest_info: nick,mail
  valine_notify: false
  valine_verify: false
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
# local_search:
#   enable: true
